name: tests
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ "1.20" ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
      - uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299
        with:
          version: v1.53
          skip-cache: true
          skip-pkg-cache: true
      - run: go mod tidy && git diff --check
      - run: make test
      - uses: github/codeql-action/init@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2
        with:
          languages: go
      - uses: github/codeql-action/analyze@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2
